[package]
name = "adventofcode"
version = "0.1.0"
authors = ["Pelle MÃ¥nsson <pelle.mansson@attentec.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
